# Generated by Django 5.1.3 on 2025-01-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0015_alter_product_category_product_sale_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="discount",
        ),
        migrations.AddField(
            model_name="voucher",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="discount_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="minimum_order_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
