# Generated by Django 5.1.3 on 2025-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0016_remove_voucher_discount_voucher_brand_and_more"),
    ]

    operations = [
    
        migrations.AddField(
            model_name="voucher",
            name="brand_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("out_of_stock", "Out of Stock")],
                default="available",
                max_length=20,
            ),
        ),
    ]
