# Generated by Django 5.1.4 on 2025-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0017_reward_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
