# Generated by Django 5.1.3 on 2025-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0017_remove_voucher_brand_voucher_brand_id_and_more"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="voucher",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
