# Generated by Django 5.1.3 on 2025-01-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0019_brand_remove_voucher_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="brand_id",
        ),
    ]
