# Generated by Django 5.1.4 on 2025-01-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0020_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
    ]
