# Generated by Django 5.1.3 on 2025-01-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0020_remove_voucher_brand_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
