# Generated by Django 5.1.3 on 2025-01-11 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0021_remove_product_stock_product_quantity"),
    ]

    operations = [
        # Bình luận hoặc xóa dòng này nếu gặp lỗi khi chạy migrate
        # migrations.RemoveField(
        #     model_name="cartitem",
        #     name="cart",
        # ),

        
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sua_bot_dinh_duong", "Sữa bột dinh dưỡng"),
                    ("ta_bim_cho_be", "Tả bỉm cho bé"),
                    ("hang_ban_chay", "Hàng bán chạy"),
                    ("hang_khuyen_mai", "Hàng khuyến mãi"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("con_hang", "Còn hàng"), ("het_hang", "Hết hàng")],
                default="available",
                max_length=20,
            ),
        ),
        # Bình luận hoặc xóa dòng này nếu gặp lỗi khi chạy migrate
        # migrations.DeleteModel(
        #     name="Cart",
        # ),
    ]
