# Generated by Django 5.1.3 on 2025-01-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0023_reward_remove_cartitem_cart_remove_product_image_and_more"),
    ]

    operations = [
       
    ]
