# Generated by Django 5.1.3 on 2025-01-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0024_remove_cartitem_cart"),
    ]

    operations = [
        
       
    ]
