# Generated by Django 5.1.3 on 2025-01-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0026_remove_cartitem_cart"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="cartitem",
        #     name="cart",
        # ),
        # migrations.DeleteModel(
        #     name="Cart",
        # ),
    ]
