# Generated by Django 5.1.4 on 2025-01-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0027_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
