# Generated by Django 5.1.3 on 2025-01-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0027_remove_cartitem_cart_delete_cart"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="cartitem",
        #     name="cart",
        # ),
        # migrations.RemoveField(
        #     model_name="product",
        #     name="image",
        # ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        # migrations.DeleteModel(
        #     name="Cart",
        # ),
    ]
