# Generated by Django 5.1.5 on 2025-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0028_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank_transfer', 'Chuyển khoản ngân hàng')], default='cod', max_length=20),
        ),
    ]
