# Generated by Django 5.1.3 on 2024-12-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0007_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
    ]
