# Generated by Django 5.1.3 on 2024-12-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0010_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
