# Generated by Django 5.1.3 on 2024-12-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webbansua", "0011_product_image_product_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="webbansua_customuser",
        ),
    ]
