# Generated by Django 5.1.4 on 2025-01-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0018_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
