# Generated by Django 5.1.4 on 2025-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0021_remove_cartitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
