# Generated by Django 5.1.4 on 2025-01-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0023_alter_customuser_options_remove_customuser_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
