# Generated by Django 5.1.4 on 2025-01-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbansua', '0024_remove_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percent',
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
